"""Domain exceptions. Every error is typed — no silent failures."""
from __future__ import annotations


class ThetaGainersError(Exception):
    """Base class for all app errors."""


# ── Auth ─────────────────────────────────────────────────────────────────────
class AuthError(ThetaGainersError): ...
class InvalidCredentials(AuthError): ...
class InvalidTOTP(AuthError): ...
class IPNotAllowed(AuthError): ...
class TokenExpired(AuthError): ...
class InsufficientRole(AuthError): ...


# ── Broker ───────────────────────────────────────────────────────────────────
class BrokerError(ThetaGainersError): ...
class BrokerDown(BrokerError): ...
class BrokerSessionExpired(BrokerError): ...
class OrderRejected(BrokerError): ...
class InsufficientMargin(BrokerError): ...
class InvalidSymbol(BrokerError): ...


# ── Risk / Compliance ────────────────────────────────────────────────────────
class RiskViolation(ThetaGainersError): ...
class LotCapExceeded(RiskViolation): ...
class DailyLossCapExceeded(RiskViolation): ...
class ActiveStrategiesCapExceeded(RiskViolation): ...
class FatFingerGuard(RiskViolation): ...
class SEBIRateLimitExceeded(RiskViolation): ...
class OTRThresholdBreached(RiskViolation): ...
class FreezeQtyExceeded(RiskViolation): ...
class IlliquidStrike(RiskViolation): ...
class CircuitBreakerTripped(RiskViolation): ...
class CoolingOffActive(RiskViolation): ...
class DeadManSwitchFired(RiskViolation): ...
class TwoPersonApprovalRequired(RiskViolation): ...


# ── Strategy / Execution ─────────────────────────────────────────────────────
class StrategyError(ThetaGainersError): ...
class InvalidStateTransition(StrategyError): ...
class PositionMismatch(StrategyError): ...
class PartialFillUnrecoverable(StrategyError): ...
